# Generated by Django 5.0.6 on 2025-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverynotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee_uzs', models.PositiveIntegerField(default=10000)),
                ('per_km_fee_uzs', models.PositiveIntegerField(default=2000)),
                ('min_fee_uzs', models.PositiveIntegerField(default=10000)),
                ('max_fee_uzs', models.PositiveIntegerField(default=60000)),
                ('free_over_uzs', models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirilsa, chegirma yo'q", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yetkazib berish sozlamasi',
                'verbose_name_plural': 'Yetkazib berish sozlamalari',
            },
        ),
    ]
