# Generated by Django 5.0.6 on 2025-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shop_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='shop_location_link',
            field=models.URLField(blank=True, default='', verbose_name='Do‘kon manzili (havola)'),
        ),
    ]
